-- ============================================================
-- SYNCHRONISATION DU REGISTRE SPONSORS (127 sponsors)
--
-- Reprend le catalogue TypeScript cycling-manager/data/sponsors.
-- Equivalent SQL de « npm run sponsors:sync », a executer dans
-- l'editeur SQL Supabase. Idempotent : rejouable sans risque.
-- Aucun sponsor n'est supprime, l'historique des offres et des
-- contrats est donc preserve.
-- ============================================================

begin;

with catalog (catalog_key, name, short_name, industry, country_code) as (
  values
    ('atlas-solaire', 'Atlas Solaire', 'Atlas Solaire', 'Énergie solaire et mobilité', 'MA'),
    ('teranga-ocean', 'Teranga Océan', 'Teranga', 'Transport maritime et logistique', 'SN'),
    ('ivoire-cacao', 'Ivoire Cacao', 'Ivoire Cacao', 'Cacao et agroalimentaire', 'CI'),
    ('naija-pulse', 'Naija Pulse', 'Naija Pulse', 'Fintech et mobilité connectée', 'NG'),
    ('mboa-horizon', 'Mboa Horizon', 'Mboa', 'Infrastructures et gestion forestière', 'CM'),
    ('rift-motion', 'Rift Motion', 'Rift Motion', 'Ingénierie et mobilité', 'KE'),
    ('kaffa-origins', 'Kaffa Origins', 'Kaffa', 'Café et agroforesterie', 'ET'),
    ('mille-collines-tech', 'Mille Collines Tech', 'Mille Collines', 'Technologies et infrastructures numériques', 'RW'),
    ('ubuntu-rail', 'Ubuntu Rail', 'Ubuntu Rail', 'Transport ferroviaire et ingénierie', 'ZA'),
    ('zebu-routes', 'Zebu Routes', 'Zebu Routes', 'Tourisme durable et logistique', 'MG'),
    ('eichenrad-automobil', 'Eichenrad Automobil', 'Eichenrad', 'Constructeur automobile premium', 'DE'),
    ('soramei-motors', 'Soramei Motors', 'Soramei', 'Constructeur automobile technologique', 'JP'),
    ('mesa-forge-automotive', 'Mesa Forge Automotive', 'Mesa Forge', 'Constructeur automobile et utilitaire', 'US'),
    ('hanul-vector-motors', 'Hanul Vector Motors', 'Hanul Vector', 'Constructeur de mobilité électrique', 'KR'),
    ('jade-meridian-motors', 'Jade Meridian Motors', 'Jade Meridian', 'Constructeur automobile international', 'CN'),
    ('fulmine-rosso-automobili', 'Fulmine Rosso Automobili', 'Fulmine Rosso', 'Constructeur de voitures sportives', 'IT'),
    ('mistralys-automobiles', 'Mistralys Automobiles', 'Mistralys', 'Constructeur automobile généraliste', 'FR'),
    ('calder-wren-motorworks', 'Calder & Wren Motorworks', 'Calder & Wren', 'Manufacture automobile britannique', 'GB'),
    ('suryavaan-motors', 'Suryavaan Motors', 'Suryavaan', 'Constructeur de mobilité accessible', 'IN'),
    ('vereda-nova-automoveis', 'Vereda Nova Automóveis', 'Vereda Nova', 'Constructeur automobile sud-américain', 'BR'),
    ('koit-systems', 'Koit Systems', 'Koit', 'Infrastructure numérique et cybersécurité', 'EE'),
    ('saare-windworks', 'Saare Windworks', 'Saare', 'Éolien offshore et ingénierie maritime', 'EE'),
    ('daugava-transit', 'Daugava Transit', 'Daugava', 'Transport ferroviaire et logistique', 'LV'),
    ('amber-rye-foods', 'Amber Rye Foods', 'Amber Rye', 'Agriculture et agroalimentaire', 'LV'),
    ('nemunas-photonics', 'Nemunas Photonics', 'Nemunas', 'Photonique, lasers et optique', 'LT'),
    ('montbrun-private', 'Montbrun Private', 'Montbrun', 'Banque privée et gestion de patrimoine', 'CH'),
    ('straits-ledger', 'Straits Ledger', 'Straits Ledger', 'Banque numérique et financement du commerce', 'SG'),
    ('rio-sur-credito', 'Río Sur Crédito', 'Río Sur', 'Crédit coopératif et financement agricole', 'UY'),
    ('dodo-blue-finance', 'Dodo Blue Finance', 'Dodo Blue', 'Crédit maritime et financement du commerce', 'MU'),
    ('han-river-credit', 'Han River Credit', 'Han River', 'Crédit technologique et banque mobile', 'KR'),
    ('boreal-mutual', 'Boreal Mutual', 'Boreal Mutual', 'Banque mutualiste et crédit aux entreprises', 'CA'),
    ('nomad-vault', 'Nomad Vault', 'Nomad Vault', 'Banque d’investissement et infrastructures', 'KZ'),
    ('lakbay-credit', 'Lakbay Credit', 'Lakbay Credit', 'Microcrédit, transferts et banque mobile', 'PH'),
    ('ardennes-outillage', 'Ardennes Outillage', 'Ardennes', 'Outillage industriel', 'BE'),
    ('veloria-bank', 'Veloria Bank', 'Veloria', 'Banque et finance', 'BE'),
    ('nordika-glass', 'Nordika Glass', 'Nordika', 'Industrie du verre', 'BE'),
    ('brassel-foods', 'Brassel Foods', 'Brassel', 'Agroalimentaire', 'BE'),
    ('lumen-energy', 'Lumen Energy', 'Lumen', 'Énergie renouvelable', 'BE'),
    ('azur-logistics', 'Azur Logistics', 'Azur', 'Transport et logistique', 'BE'),
    ('abbaye-du-lion', 'Abbaye du Lion', 'Abbaye du Lion', 'Brasserie artisanale', 'BE'),
    ('boardwalk-taffy', 'Boardwalk Taffy', 'Boardwalk', 'Confiserie et douceurs artisanales', 'US'),
    ('jade-lantern-candy', 'Jade Lantern Candy', 'Jade Lantern', 'Confiserie et cadeaux gourmands', 'CN'),
    ('baobab-bonbons', 'Baobab Bonbons', 'Baobab', 'Confiserie fruitière et vanille', 'MG'),
    ('indus-mithai', 'Indus Mithai', 'Indus Mithai', 'Mithai et pâtisserie traditionnelle', 'PK'),
    ('doce-brisa', 'Doce Brisa', 'Doce Brisa', 'Confiserie tropicale et chocolat', 'BR'),
    ('nordlys-lakrids', 'Nordlys Lakrids', 'Nordlys', 'Réglisse et confiserie nordique', 'DK'),
    ('aurora-racing-team', 'Aurora Racing Team', 'Aurora Racing', 'Projet cycliste haute performance', 'FI'),
    ('pura-cadencia-test-team', 'Pura Cadencia Test Team', 'Pura Cadencia', 'Laboratoire cycliste d’altitude', 'CO'),
    ('bohemia-velocity-project', 'Bohemia Velocity Project', 'Bohemia Velocity', 'Projet de développement cycliste', 'CZ'),
    ('atlas-racing-lab', 'Atlas Racing Lab', 'Atlas Racing Lab', 'Centre d’essais cyclistes', 'MA'),
    ('koru-racing-collective', 'Koru Racing Collective', 'Koru Racing', 'Collectif cycliste de développement', 'NZ'),
    ('danube-test-team', 'Danube Test Team', 'Danube Test Team', 'Équipe laboratoire aérodynamique', 'AT'),
    ('savana-racing-project', 'Savana Racing Project', 'Savana Racing', 'Projet cycliste régional', 'KE'),
    ('orion-cycling-lab', 'Orion Cycling Lab', 'Orion Cycling Lab', 'Laboratoire cycliste méditerranéen', 'CY'),
    ('quebec-nord-racing', 'Québec Nord Racing', 'Québec Nord', 'Équipe cycliste de développement', 'CA'),
    ('garuda-test-team', 'Garuda Test Team', 'Garuda Test Team', 'Équipe-test cycliste tropicale', 'ID'),
    ('petrolove', 'Petrolove', 'Petrolove', 'Hydrocarbures et énergie intégrée', 'VE'),
    ('steppe-current', 'Steppe Current', 'Steppe Current', 'Éolien et hydrogène vert', 'MN'),
    ('himal-hydro', 'Himal Hydro', 'Himal Hydro', 'Hydroélectricité et micro-réseaux', 'NP'),
    ('kalahari-helio', 'Kalahari Helio', 'Kalahari Helio', 'Solaire thermodynamique et hydrogène', 'NA'),
    ('kartli-grid', 'Kartli Grid', 'Kartli Grid', 'Réseaux électriques et stockage hydraulique', 'GE'),
    ('viti-tideworks', 'Viti Tideworks', 'Viti Tideworks', 'Énergie marémotrice et micro-réseaux insulaires', 'FJ'),
    ('fugazza-sprint', 'Fugazza Sprint', 'Fugazza', 'Pizzeria rapide et spécialités porteñas', 'AR'),
    ('okavango-stack', 'Okavango Stack', 'Okavango', 'Burgers grillés et restauration rapide', 'BW'),
    ('bosphore-ember', 'Bosphore Ember', 'Bosphore', 'Kebab, döner et grillades rapides', 'TR'),
    ('siam-wokline', 'Siam Wokline', 'Siam Wokline', 'Wok, nouilles et cuisine thaïlandaise rapide', 'TH'),
    ('lima-maki', 'Lima Maki', 'Lima Maki', 'Sushi nikkei et restauration rapide', 'PE'),
    ('cedar-mezze', 'Cedar Mezze', 'Cedar Mezze', 'Shawarma, falafel et mezzés rapides', 'LB'),
    ('adria-pasta-bar', 'Adria Pasta Bar', 'Adria Pasta', 'Pâtes fraîches et restauration rapide', 'HR'),
    ('island-ember', 'Island Ember', 'Island Ember', 'Poulet jerk et friture rapide', 'JM'),
    ('maiz-rapido', 'Maíz Rápido', 'Maíz Rápido', 'Tacos, maïs et cuisine mexicaine rapide', 'MX'),
    ('cook-strait-fry', 'Cook Strait Fry', 'Cook Strait', 'Fish and chips et produits de la mer', 'NZ'),
    ('veloria-mobilites', 'Veloria Mobilités', 'Veloria', 'Mobilité et transports', 'FR'),
    ('terroirs-unis', 'Terroirs Unis', 'Terroirs', 'Agroalimentaire', 'FR'),
    ('hexa-batiment', 'Hexa Bâtiment', 'Hexa', 'Construction', 'FR'),
    ('nova-assurances', 'Nova Assurances', 'Nova', 'Assurance', 'FR'),
    ('kyklos-ferries', 'Kyklos Ferries', 'Kyklos', 'Transport maritime et tourisme', 'GR'),
    ('delphi-dynamics', 'Delphi Dynamics', 'Delphi', 'Technologies avancées et données', 'GR'),
    ('kriti-gea', 'Kriti Gea', 'Kriti Gea', 'Agriculture et agroalimentaire', 'GR'),
    ('hephaistos-forge', 'Hephaistos Forge', 'Hephaistos', 'Métallurgie et ingénierie', 'GR'),
    ('nisos-energia', 'Nisos Energeia', 'Nisos', 'Énergies renouvelables', 'GR'),
    ('veloce-motori', 'Veloce Motori', 'Veloce', 'Automobile et mobilité électrique', 'IT'),
    ('aurelia-moda', 'Aurelia Moda', 'Aurelia', 'Mode et luxe', 'IT'),
    ('adriatica-lines', 'Adriatica Lines', 'Adriatica', 'Transport maritime et logistique', 'IT'),
    ('ferrovia-nova', 'Ferrovia Nova', 'Ferrovia', 'Ingénierie ferroviaire', 'IT'),
    ('pietra-energia', 'Pietra Energia', 'Pietra', 'Énergie géothermique', 'IT'),
    ('granito-ceramiche', 'Granito Ceramiche', 'Granito', 'Céramique et design architectural', 'IT'),
    ('stella-caffe', 'Stella Caffè', 'Stella', 'Café et torréfaction', 'IT'),
    ('dolci-bellini', 'Dolci Bellini', 'Bellini', 'Confiserie', 'IT'),
    ('oliva-verde', 'Oliva Verde', 'Oliva Verde', 'Huile d’olive et agroalimentaire', 'IT'),
    ('riviera-viva', 'Riviera Viva', 'Riviera Viva', 'Tourisme et hôtellerie', 'IT'),
    ('hinode-transit', 'Hinode Transit', 'Hinode', 'Mobilité ferroviaire et infrastructures', 'JP'),
    ('setouchi-marine', 'Setouchi Marine', 'Setouchi', 'Transport maritime et logistique insulaire', 'JP'),
    ('tsubame-precision', 'Tsubame Precision', 'Tsubame', 'Métallurgie de précision et composants', 'JP'),
    ('uji-midori', 'Uji Midori', 'Uji Midori', 'Thé, agriculture et agroalimentaire', 'JP'),
    ('yukikaze-outdoor', 'Yukikaze Outdoor', 'Yukikaze', 'Équipement outdoor et textiles techniques', 'JP'),
    ('deltaflow-engineering', 'DeltaFlow Engineering', 'DeltaFlow', 'Génie hydraulique', 'NL'),
    ('tulipa-flora', 'Tulipa Flora', 'Tulipa Flora', 'Horticulture', 'NL'),
    ('orange-freight', 'Orange Freight', 'Orange Freight', 'Transport et logistique', 'NL'),
    ('urbanride-mobility', 'UrbanRide Mobility', 'UrbanRide', 'Mobilité douce', 'NL'),
    ('windmill-foods', 'WindMill Foods', 'WindMill', 'Agroalimentaire', 'NL'),
    ('atlantica-naval-systems', 'Atlântica Naval Systems', 'Atlântica', 'Ingénierie maritime', 'PT'),
    ('cortica-nova', 'Cortiça Nova', 'Cortiça', 'Matériaux en liège', 'PT'),
    ('azulejo-vivo', 'Azulejo Vivo', 'Azulejo', 'Céramique et design', 'PT'),
    ('tejo-telecom', 'Tejo Telecom', 'Tejo', 'Télécommunications', 'PT'),
    ('serra-dourada-foods', 'Serra Dourada Foods', 'Serra Dourada', 'Agroalimentaire méditerranéen', 'PT'),
    ('nordhavn-post', 'Nordhavn Post', 'Nordhavn Post', 'Services postaux nordiques', 'DK'),
    ('qhapaq-mail', 'Qhapaq Mail', 'Qhapaq Mail', 'Courrier express andin', 'PE'),
    ('kapuluan-post', 'Kapuluan Post', 'Kapuluan Post', 'Services postaux insulaires', 'PH'),
    ('sahel-colis', 'Sahel Colis', 'Sahel Colis', 'Livraison postale régionale', 'SN'),
    ('triglav-parcel', 'Triglav Parcel', 'Triglav Parcel', 'Messagerie et colis alpins', 'SI'),
    ('sol-del-sur', 'Sol del Sur', 'Sol', 'Énergie solaire', 'ES'),
    ('glen-durnach', 'Glen Durnach', 'Glen Durnach', 'Whisky écossais single malt', 'GB'),
    ('dhoni-reef', 'Dhoni Reef', 'Dhoni Reef', 'Rhum brun des îles', 'MV'),
    ('vistula-no9', 'Vistula No.9', 'Vistula No.9', 'Vodka premium', 'PL'),
    ('cobre-agave', 'Cobre Agave', 'Cobre Agave', 'Tequila d’agave', 'MX'),
    ('cape-fynbos', 'Cape Fynbos', 'Cape Fynbos', 'Gin botanique', 'ZA'),
    ('apricot-crown', 'Apricot Crown', 'Apricot Crown', 'Brandy arménien', 'AM'),
    ('serra-de-fogo', 'Serra de Fogo', 'Serra de Fogo', 'Cachaça artisanale', 'BR'),
    ('jade-kiln', 'Jade Kiln', 'Jade Kiln', 'Baijiu premium', 'CN'),
    ('cedar-moon', 'Cedar Moon', 'Cedar Moon', 'Arak traditionnel', 'LB'),
    ('atacama-condor', 'Atacama Condor', 'Atacama Condor', 'Pisco chilien', 'CL'),
    ('great-lakes-foundry', 'Great Lakes Foundry', 'Great Lakes', 'Métallurgie et industrie lourde', 'US'),
    ('redwood-circuits', 'Redwood Circuits', 'Redwood', 'Technologies et semi-conducteurs', 'US'),
    ('canyon-volt', 'Canyon Volt', 'Canyon Volt', 'Énergies renouvelables et mobilité', 'US'),
    ('harborline-logistics', 'Harborline Logistics', 'Harborline', 'Logistique portuaire et transport', 'US'),
    ('prairie-biofoods', 'Prairie Biofoods', 'Prairie', 'Agriculture et agroalimentaire', 'US')
)
insert into public.sponsors (
  catalog_key,
  country_id,
  name,
  short_name,
  industry,
  status
)
select
  catalog.catalog_key,
  country.id,
  catalog.name,
  catalog.short_name,
  catalog.industry,
  'active'
from catalog
join public.countries as country
  on country.iso_alpha2 = catalog.country_code
  and country.is_active
on conflict (catalog_key) do update set
  country_id = excluded.country_id,
  name = excluded.name,
  short_name = excluded.short_name,
  industry = excluded.industry,
  status = 'active';

commit;
