begin;

-- ============================================================
-- RÉFÉRENTIEL DES PAYS
-- Liste ISO 3166-1 complète, avec noms français.
-- nationality_label reste volontairement NULL dans cette première
-- version : l'interface utilisera le nom du pays pour le choix de
-- la nationalité. Les gentilés pourront être enrichis ultérieurement.
-- ============================================================

insert into public.countries (
  name,
  iso_alpha2,
  iso_alpha3,
  nationality_label,
  is_active
)
values
  ('Afghanistan', 'AF', 'AFG', null, true),
  ('Afrique du Sud', 'ZA', 'ZAF', null, true),
  ('Albanie', 'AL', 'ALB', null, true),
  ('Algérie', 'DZ', 'DZA', null, true),
  ('Allemagne', 'DE', 'DEU', null, true),
  ('Andorre', 'AD', 'AND', null, true),
  ('Angola', 'AO', 'AGO', null, true),
  ('Anguilla', 'AI', 'AIA', null, true),
  ('Antarctique', 'AQ', 'ATA', null, true),
  ('Antigua-et-Barbuda', 'AG', 'ATG', null, true),
  ('Arabie saoudite', 'SA', 'SAU', null, true),
  ('Argentine', 'AR', 'ARG', null, true),
  ('Arménie', 'AM', 'ARM', null, true),
  ('Aruba', 'AW', 'ABW', null, true),
  ('Australie', 'AU', 'AUS', null, true),
  ('Autriche', 'AT', 'AUT', null, true),
  ('Azerbaïdjan', 'AZ', 'AZE', null, true),
  ('Bahamas', 'BS', 'BHS', null, true),
  ('Bahreïn', 'BH', 'BHR', null, true),
  ('Bangladesh', 'BD', 'BGD', null, true),
  ('Barbade', 'BB', 'BRB', null, true),
  ('Belgique', 'BE', 'BEL', null, true),
  ('Belize', 'BZ', 'BLZ', null, true),
  ('Bermudes', 'BM', 'BMU', null, true),
  ('Bhoutan', 'BT', 'BTN', null, true),
  ('Biélorussie', 'BY', 'BLR', null, true),
  ('Bolivie', 'BO', 'BOL', null, true),
  ('Bosnie-Herzégovine', 'BA', 'BIH', null, true),
  ('Botswana', 'BW', 'BWA', null, true),
  ('Brunei', 'BN', 'BRN', null, true),
  ('Brésil', 'BR', 'BRA', null, true),
  ('Bulgarie', 'BG', 'BGR', null, true),
  ('Burkina Faso', 'BF', 'BFA', null, true),
  ('Burundi', 'BI', 'BDI', null, true),
  ('Bénin', 'BJ', 'BEN', null, true),
  ('Cambodge', 'KH', 'KHM', null, true),
  ('Cameroun', 'CM', 'CMR', null, true),
  ('Canada', 'CA', 'CAN', null, true),
  ('Cap-Vert', 'CV', 'CPV', null, true),
  ('Chili', 'CL', 'CHL', null, true),
  ('Chine', 'CN', 'CHN', null, true),
  ('Chypre', 'CY', 'CYP', null, true),
  ('Colombie', 'CO', 'COL', null, true),
  ('Comores', 'KM', 'COM', null, true),
  ('Congo-Brazzaville', 'CG', 'COG', null, true),
  ('Congo-Kinshasa', 'CD', 'COD', null, true),
  ('Corée du Nord', 'KP', 'PRK', null, true),
  ('Corée du Sud', 'KR', 'KOR', null, true),
  ('Costa Rica', 'CR', 'CRI', null, true),
  ('Croatie', 'HR', 'HRV', null, true),
  ('Cuba', 'CU', 'CUB', null, true),
  ('Curaçao', 'CW', 'CUW', null, true),
  ('Côte d’Ivoire', 'CI', 'CIV', null, true),
  ('Danemark', 'DK', 'DNK', null, true),
  ('Djibouti', 'DJ', 'DJI', null, true),
  ('Dominique', 'DM', 'DMA', null, true),
  ('Espagne', 'ES', 'ESP', null, true),
  ('Estonie', 'EE', 'EST', null, true),
  ('Eswatini', 'SZ', 'SWZ', null, true),
  ('Fidji', 'FJ', 'FJI', null, true),
  ('Finlande', 'FI', 'FIN', null, true),
  ('France', 'FR', 'FRA', null, true),
  ('Gabon', 'GA', 'GAB', null, true),
  ('Gambie', 'GM', 'GMB', null, true),
  ('Ghana', 'GH', 'GHA', null, true),
  ('Gibraltar', 'GI', 'GIB', null, true),
  ('Grenade', 'GD', 'GRD', null, true),
  ('Groenland', 'GL', 'GRL', null, true),
  ('Grèce', 'GR', 'GRC', null, true),
  ('Guadeloupe', 'GP', 'GLP', null, true),
  ('Guam', 'GU', 'GUM', null, true),
  ('Guatemala', 'GT', 'GTM', null, true),
  ('Guernesey', 'GG', 'GGY', null, true),
  ('Guinée', 'GN', 'GIN', null, true),
  ('Guinée équatoriale', 'GQ', 'GNQ', null, true),
  ('Guinée-Bissau', 'GW', 'GNB', null, true),
  ('Guyana', 'GY', 'GUY', null, true),
  ('Guyane française', 'GF', 'GUF', null, true),
  ('Géorgie', 'GE', 'GEO', null, true),
  ('Géorgie du Sud-et-les Îles Sandwich du Sud', 'GS', 'SGS', null, true),
  ('Haïti', 'HT', 'HTI', null, true),
  ('Honduras', 'HN', 'HND', null, true),
  ('Hongrie', 'HU', 'HUN', null, true),
  ('Inde', 'IN', 'IND', null, true),
  ('Indonésie', 'ID', 'IDN', null, true),
  ('Irak', 'IQ', 'IRQ', null, true),
  ('Iran', 'IR', 'IRN', null, true),
  ('Irlande', 'IE', 'IRL', null, true),
  ('Islande', 'IS', 'ISL', null, true),
  ('Israël', 'IL', 'ISR', null, true),
  ('Italie', 'IT', 'ITA', null, true),
  ('Jamaïque', 'JM', 'JAM', null, true),
  ('Japon', 'JP', 'JPN', null, true),
  ('Jersey', 'JE', 'JEY', null, true),
  ('Jordanie', 'JO', 'JOR', null, true),
  ('Kazakhstan', 'KZ', 'KAZ', null, true),
  ('Kenya', 'KE', 'KEN', null, true),
  ('Kirghizstan', 'KG', 'KGZ', null, true),
  ('Kiribati', 'KI', 'KIR', null, true),
  ('Koweït', 'KW', 'KWT', null, true),
  ('La Réunion', 'RE', 'REU', null, true),
  ('Laos', 'LA', 'LAO', null, true),
  ('Lesotho', 'LS', 'LSO', null, true),
  ('Lettonie', 'LV', 'LVA', null, true),
  ('Liban', 'LB', 'LBN', null, true),
  ('Liberia', 'LR', 'LBR', null, true),
  ('Libye', 'LY', 'LBY', null, true),
  ('Liechtenstein', 'LI', 'LIE', null, true),
  ('Lituanie', 'LT', 'LTU', null, true),
  ('Luxembourg', 'LU', 'LUX', null, true),
  ('Macédoine du Nord', 'MK', 'MKD', null, true),
  ('Madagascar', 'MG', 'MDG', null, true),
  ('Malaisie', 'MY', 'MYS', null, true),
  ('Malawi', 'MW', 'MWI', null, true),
  ('Maldives', 'MV', 'MDV', null, true),
  ('Mali', 'ML', 'MLI', null, true),
  ('Malte', 'MT', 'MLT', null, true),
  ('Maroc', 'MA', 'MAR', null, true),
  ('Martinique', 'MQ', 'MTQ', null, true),
  ('Maurice', 'MU', 'MUS', null, true),
  ('Mauritanie', 'MR', 'MRT', null, true),
  ('Mayotte', 'YT', 'MYT', null, true),
  ('Mexique', 'MX', 'MEX', null, true),
  ('Micronésie', 'FM', 'FSM', null, true),
  ('Moldavie', 'MD', 'MDA', null, true),
  ('Monaco', 'MC', 'MCO', null, true),
  ('Mongolie', 'MN', 'MNG', null, true),
  ('Montserrat', 'MS', 'MSR', null, true),
  ('Monténégro', 'ME', 'MNE', null, true),
  ('Mozambique', 'MZ', 'MOZ', null, true),
  ('Myanmar (Birmanie)', 'MM', 'MMR', null, true),
  ('Namibie', 'NA', 'NAM', null, true),
  ('Nauru', 'NR', 'NRU', null, true),
  ('Nicaragua', 'NI', 'NIC', null, true),
  ('Niger', 'NE', 'NER', null, true),
  ('Nigeria', 'NG', 'NGA', null, true),
  ('Niue', 'NU', 'NIU', null, true),
  ('Norvège', 'NO', 'NOR', null, true),
  ('Nouvelle-Calédonie', 'NC', 'NCL', null, true),
  ('Nouvelle-Zélande', 'NZ', 'NZL', null, true),
  ('Népal', 'NP', 'NPL', null, true),
  ('Oman', 'OM', 'OMN', null, true),
  ('Ouganda', 'UG', 'UGA', null, true),
  ('Ouzbékistan', 'UZ', 'UZB', null, true),
  ('Pakistan', 'PK', 'PAK', null, true),
  ('Palaos', 'PW', 'PLW', null, true),
  ('Panama', 'PA', 'PAN', null, true),
  ('Papouasie-Nouvelle-Guinée', 'PG', 'PNG', null, true),
  ('Paraguay', 'PY', 'PRY', null, true),
  ('Pays-Bas', 'NL', 'NLD', null, true),
  ('Pays-Bas caribéens', 'BQ', 'BES', null, true),
  ('Philippines', 'PH', 'PHL', null, true),
  ('Pologne', 'PL', 'POL', null, true),
  ('Polynésie française', 'PF', 'PYF', null, true),
  ('Porto Rico', 'PR', 'PRI', null, true),
  ('Portugal', 'PT', 'PRT', null, true),
  ('Pérou', 'PE', 'PER', null, true),
  ('Qatar', 'QA', 'QAT', null, true),
  ('R.A.S. chinoise de Hong Kong', 'HK', 'HKG', null, true),
  ('R.A.S. chinoise de Macao', 'MO', 'MAC', null, true),
  ('Roumanie', 'RO', 'ROU', null, true),
  ('Royaume-Uni', 'GB', 'GBR', null, true),
  ('Russie', 'RU', 'RUS', null, true),
  ('Rwanda', 'RW', 'RWA', null, true),
  ('République centrafricaine', 'CF', 'CAF', null, true),
  ('République dominicaine', 'DO', 'DOM', null, true),
  ('Sahara occidental', 'EH', 'ESH', null, true),
  ('Saint-Barthélemy', 'BL', 'BLM', null, true),
  ('Saint-Christophe-et-Niévès', 'KN', 'KNA', null, true),
  ('Saint-Marin', 'SM', 'SMR', null, true),
  ('Saint-Martin', 'MF', 'MAF', null, true),
  ('Saint-Martin (partie néerlandaise)', 'SX', 'SXM', null, true),
  ('Saint-Pierre-et-Miquelon', 'PM', 'SPM', null, true),
  ('Saint-Vincent-et-les Grenadines', 'VC', 'VCT', null, true),
  ('Sainte-Hélène', 'SH', 'SHN', null, true),
  ('Sainte-Lucie', 'LC', 'LCA', null, true),
  ('Salvador', 'SV', 'SLV', null, true),
  ('Samoa', 'WS', 'WSM', null, true),
  ('Samoa américaines', 'AS', 'ASM', null, true),
  ('Sao Tomé-et-Principe', 'ST', 'STP', null, true),
  ('Serbie', 'RS', 'SRB', null, true),
  ('Seychelles', 'SC', 'SYC', null, true),
  ('Sierra Leone', 'SL', 'SLE', null, true),
  ('Singapour', 'SG', 'SGP', null, true),
  ('Slovaquie', 'SK', 'SVK', null, true),
  ('Slovénie', 'SI', 'SVN', null, true),
  ('Somalie', 'SO', 'SOM', null, true),
  ('Soudan', 'SD', 'SDN', null, true),
  ('Soudan du Sud', 'SS', 'SSD', null, true),
  ('Sri Lanka', 'LK', 'LKA', null, true),
  ('Suisse', 'CH', 'CHE', null, true),
  ('Suriname', 'SR', 'SUR', null, true),
  ('Suède', 'SE', 'SWE', null, true),
  ('Svalbard et Jan Mayen', 'SJ', 'SJM', null, true),
  ('Syrie', 'SY', 'SYR', null, true),
  ('Sénégal', 'SN', 'SEN', null, true),
  ('Tadjikistan', 'TJ', 'TJK', null, true),
  ('Tanzanie', 'TZ', 'TZA', null, true),
  ('Taïwan', 'TW', 'TWN', null, true),
  ('Tchad', 'TD', 'TCD', null, true),
  ('Tchéquie', 'CZ', 'CZE', null, true),
  ('Terres australes françaises', 'TF', 'ATF', null, true),
  ('Territoire britannique de l’océan Indien', 'IO', 'IOT', null, true),
  ('Territoires palestiniens', 'PS', 'PSE', null, true),
  ('Thaïlande', 'TH', 'THA', null, true),
  ('Timor oriental', 'TL', 'TLS', null, true),
  ('Togo', 'TG', 'TGO', null, true),
  ('Tokelau', 'TK', 'TKL', null, true),
  ('Tonga', 'TO', 'TON', null, true),
  ('Trinité-et-Tobago', 'TT', 'TTO', null, true),
  ('Tunisie', 'TN', 'TUN', null, true),
  ('Turkménistan', 'TM', 'TKM', null, true),
  ('Turquie', 'TR', 'TUR', null, true),
  ('Tuvalu', 'TV', 'TUV', null, true),
  ('Ukraine', 'UA', 'UKR', null, true),
  ('Uruguay', 'UY', 'URY', null, true),
  ('Vanuatu', 'VU', 'VUT', null, true),
  ('Venezuela', 'VE', 'VEN', null, true),
  ('Viêt Nam', 'VN', 'VNM', null, true),
  ('Wallis-et-Futuna', 'WF', 'WLF', null, true),
  ('Yémen', 'YE', 'YEM', null, true),
  ('Zambie', 'ZM', 'ZMB', null, true),
  ('Zimbabwe', 'ZW', 'ZWE', null, true),
  ('Égypte', 'EG', 'EGY', null, true),
  ('Émirats arabes unis', 'AE', 'ARE', null, true),
  ('Équateur', 'EC', 'ECU', null, true),
  ('Érythrée', 'ER', 'ERI', null, true),
  ('État de la Cité du Vatican', 'VA', 'VAT', null, true),
  ('États-Unis', 'US', 'USA', null, true),
  ('Éthiopie', 'ET', 'ETH', null, true),
  ('Île Bouvet', 'BV', 'BVT', null, true),
  ('Île Christmas', 'CX', 'CXR', null, true),
  ('Île de Man', 'IM', 'IMN', null, true),
  ('Île Norfolk', 'NF', 'NFK', null, true),
  ('Îles Caïmans', 'KY', 'CYM', null, true),
  ('Îles Cocos', 'CC', 'CCK', null, true),
  ('Îles Cook', 'CK', 'COK', null, true),
  ('Îles Féroé', 'FO', 'FRO', null, true),
  ('Îles Heard-et-MacDonald', 'HM', 'HMD', null, true),
  ('Îles Malouines', 'FK', 'FLK', null, true),
  ('Îles Mariannes du Nord', 'MP', 'MNP', null, true),
  ('Îles Marshall', 'MH', 'MHL', null, true),
  ('Îles mineures éloignées des États-Unis', 'UM', 'UMI', null, true),
  ('Îles Pitcairn', 'PN', 'PCN', null, true),
  ('Îles Salomon', 'SB', 'SLB', null, true),
  ('Îles Turques-et-Caïques', 'TC', 'TCA', null, true),
  ('Îles Vierges britanniques', 'VG', 'VGB', null, true),
  ('Îles Vierges des États-Unis', 'VI', 'VIR', null, true),
  ('Îles Åland', 'AX', 'ALA', null, true)
on conflict (iso_alpha2)
do update set
  name = excluded.name,
  iso_alpha3 = excluded.iso_alpha3,
  nationality_label = excluded.nationality_label,
  is_active = excluded.is_active;

commit;
